import type { OperatorInfo } from "./chargers";

export const OPERATOR_INFO: Record<string, OperatorInfo> = {
  "Tesla": { website: "https://www.tesla.com/supercharger", phone: "+1-877-798-3752", email: "charging@tesla.com", app: "Tesla", appStoreUrl: "https://apps.apple.com/app/tesla/id582007913", playStoreUrl: "https://play.google.com/store/apps/details?id=com.teslamotors.tesla" },
  "Electrify America": { website: "https://www.electrifyamerica.com", phone: "+1-833-632-2778", email: "support@electrifyamerica.com", app: "Electrify America", appStoreUrl: "https://apps.apple.com/app/electrify-america/id1458030456", playStoreUrl: "https://play.google.com/store/apps/details?id=com.ea.evowner" },
  "ChargePoint": { website: "https://www.chargepoint.com", phone: "+1-888-758-4389", email: "support@chargepoint.com", app: "ChargePoint", appStoreUrl: "https://apps.apple.com/app/chargepoint/id356866743", playStoreUrl: "https://play.google.com/store/apps/details?id=com.coulombtech" },
  "IONITY": { website: "https://ionity.eu", phone: "+49-89-9545-9920", email: "support@ionity.eu", app: "IONITY", appStoreUrl: "https://apps.apple.com/app/ionity/id1435126648", playStoreUrl: "https://play.google.com/store/apps/details?id=eu.ionity.app" },
  "BP Pulse": { website: "https://www.bppulse.co.uk", phone: "+44-3300-165-116", email: "hello@bppulse.co.uk", app: "bp pulse", appStoreUrl: "https://apps.apple.com/app/bp-pulse/id1452869908", playStoreUrl: "https://play.google.com/store/apps/details?id=com.bppulse.chargemaster" },
  "GreenWay": { website: "https://www.greenway.sk", phone: "+421-2-3300-3222", email: "info@greenway.sk", app: "GreenWay", appStoreUrl: "https://apps.apple.com/app/greenway/id1439129386", playStoreUrl: "https://play.google.com/store/apps/details?id=sk.greenway.app" },
  "ZSE Drive": { website: "https://www.zsedrive.sk", phone: "+421-2-5069-1069", email: "drive@zse.sk", app: "ZSE Drive", appStoreUrl: "https://apps.apple.com/app/zse-drive/id1481614923", playStoreUrl: "https://play.google.com/store/apps/details?id=sk.zse.drive" },
  "EnBW": { website: "https://www.enbw.com/elektromobilitaet", phone: "+49-711-289-0", email: "elektromobilitaet@enbw.com", app: "EnBW mobility+", appStoreUrl: "https://apps.apple.com/app/enbw-mobility/id1267906498", playStoreUrl: "https://play.google.com/store/apps/details?id=com.enbw.mobilityplus" },
  "TotalEnergies": { website: "https://www.totalenergies.com/ev-charge", phone: "+33-1-4744-4546", email: "ev-charge@totalenergies.com", app: "TotalEnergies Charge", appStoreUrl: "https://apps.apple.com/app/totalenergies-services/id1490562621", playStoreUrl: "https://play.google.com/store/apps/details?id=com.total.tcsapp" },
  "NIO": { website: "https://www.nio.com/nio-power", phone: "+86-400-999-6046", email: "service@nio.com", app: "NIO", appStoreUrl: "https://apps.apple.com/app/nio/id1166498291", playStoreUrl: "https://play.google.com/store/apps/details?id=com.nextev.app" },
  "State Grid": { website: "https://www.e-charging.com.cn", phone: "+86-95598", email: "service@sgcc.com.cn", app: "e充电 (e-Charging)", appStoreUrl: "https://apps.apple.com/cn/app/id1149498498", playStoreUrl: "https://play.google.com/store/apps/details?id=com.sgcc.echarging" },
  "TEPCO": { website: "https://www.tepco.co.jp/ep/ev", phone: "+81-3-6373-1111", email: "ev-support@tepco.co.jp", app: "EV-TEPCO" },
  "Hyundai": { website: "https://www.hyundai.com/worldwide/en/e-pit", phone: "+82-80-600-6000", email: "epit@hyundai.com", app: "myHyundai" },
  "Tata Power": { website: "https://www.tatapowerev.com", phone: "+91-22-6765-8282", email: "evcharging@tatapower.com", app: "Tata Power EZ Charge", appStoreUrl: "https://apps.apple.com/in/app/tata-power-ez-charge/id1505498498", playStoreUrl: "https://play.google.com/store/apps/details?id=com.tatapower.ezcharge" },
  "DEWA": { website: "https://www.dewa.gov.ae/en/consumer/ev-green-charger", phone: "+971-4-601-9999", email: "customerservice@dewa.gov.ae", app: "DEWA", appStoreUrl: "https://apps.apple.com/ae/app/dewa/id632498947", playStoreUrl: "https://play.google.com/store/apps/details?id=com.dewa.mobileapp" },
  "Chargefox": { website: "https://www.chargefox.com", phone: "+61-3-8658-4065", email: "support@chargefox.com", app: "Chargefox", appStoreUrl: "https://apps.apple.com/au/app/chargefox/id1378498498", playStoreUrl: "https://play.google.com/store/apps/details?id=com.chargefox.app" },
  "Tupinambá": { website: "https://www.tupinamba.com.br", phone: "+55-11-3500-7800", email: "contato@tupinamba.com.br", app: "Tupinambá Energia" },
  "GridCars": { website: "https://www.gridcars.co.za", phone: "+27-10-590-6060", email: "info@gridcars.co.za", app: "GridCars" },
  "ZES (Zorlu)": { website: "https://zes.net", phone: "+90-850-399-0937", email: "info@zes.net", app: "ZES", appStoreUrl: "https://apps.apple.com/tr/app/zes/id1435968787", playStoreUrl: "https://play.google.com/store/apps/details?id=com.zes.android" },
  "Electromin": { website: "https://www.electromin.com", phone: "+966-920-011-159", email: "info@electromin.com", app: "Electromin" },
  "Energy Absolute": { website: "https://www.ea-anywhere.com", phone: "+66-2-248-2488", email: "info@eaanywhere.com", app: "EA Anywhere", appStoreUrl: "https://apps.apple.com/th/app/ea-anywhere/id1465798498", playStoreUrl: "https://play.google.com/store/apps/details?id=com.ea.anywhere" },
  "Petro-Canada": { website: "https://www.petro-canada.ca/en/personal/fuel/ev-charging", phone: "+1-800-668-0220", email: "evcharging@petrocanada.ca", app: "Petro-Canada EV" },
  "Circle K / Mer": { website: "https://no.mer.eco", phone: "+47-815-00-342", email: "hei@mer.eco", app: "Mer" },
  "Slovnaft": { website: "https://www.slovnaft.sk/sk/emobilita", phone: "+421-2-5859-1111", email: "emobilita@slovnaft.sk", app: "Slovnaft" },
  "OMV": { website: "https://www.omv.com/en/electromobility", phone: "+43-1-40440-0", email: "emobility@omv.com", app: "OMV myStation" },
  "MOL Plugee": { website: "https://plugee.mol.hu", phone: "+36-1-886-5050", email: "plugee@mol.hu", app: "MOL Plugee", appStoreUrl: "https://apps.apple.com/app/mol-plugee/id1508765432", playStoreUrl: "https://play.google.com/store/apps/details?id=hu.mol.plugee" },
  "Wien Energie": { website: "https://www.wienenergie.at/e-mobilitaet", phone: "+43-1-4004-0", email: "e-mobilitaet@wienenergie.at", app: "Wien Energie Tanke" },
  "Kaufland": { website: "https://www.kaufland.de/emobilitaet", phone: "+49-800-1528-352", email: "service@kaufland.de" },
  "Lidl": { website: "https://www.lidl.de/emobilitaet", phone: "+49-800-435-3361", email: "info@lidl.de" },
  "AQNIET": { website: "https://aqniet.kz", phone: "+7-7172-28-38-48", email: "info@aqniet.kz", app: "AQNIET" },
  "UzCharge": { website: "https://uzcharge.uz", phone: "+998-71-200-0071", email: "info@uzcharge.uz" },
  "EV Point Georgia": { website: "https://evpoint.ge", phone: "+995-322-43-44-45", email: "info@evpoint.ge", app: "EV Point" },
};
