import type { ChargerStation } from "./chargers";

export const MOCK_CHARGERS: ChargerStation[] = [
  {
    id: "m1",
    title: "Aupark Shopping Center",
    operator: "ZSE Drive",
    address: "Einsteinova 18",
    city: "Bratislava",
    country: "SK",
    lat: 48.1352,
    lng: 17.1067,
    status: "operational",
    usageType: "public",
    connections: [
      { connectorType: "CCS2", powerKw: 150, voltageV: 400, ampereA: 375, currentType: "DC", quantity: 2 },
      { connectorType: "Type2", powerKw: 22, voltageV: 400, ampereA: 32, currentType: "AC", quantity: 2 },
    ],
    totalPoints: 4,
    maxPowerKw: 150,
    powerLevel: "dc_ultra",
    costInfo: "0.39 €/kWh",
    openHours: "24/7",
    rating: 4.5,
    lastVerified: "2026-05-10",
    photoUrl: null,
  },
  {
    id: "m2",
    title: "Avion Shopping Park",
    operator: "GreenWay",
    address: "Ivanská cesta 16",
    city: "Bratislava",
    country: "SK",
    lat: 48.1693,
    lng: 17.1857,
    status: "operational",
    usageType: "public",
    connections: [
      { connectorType: "CCS2", powerKw: 75, voltageV: 400, ampereA: 187, currentType: "DC", quantity: 2 },
      { connectorType: "CHAdeMO", powerKw: 50, voltageV: 400, ampereA: 125, currentType: "DC", quantity: 1 },
      { connectorType: "Type2", powerKw: 22, voltageV: 400, ampereA: 32, currentType: "AC", quantity: 4 },
    ],
    totalPoints: 7,
    maxPowerKw: 75,
    powerLevel: "dc_fast",
    costInfo: "0.35 €/kWh",
    openHours: "06:00–23:00",
    rating: 4.2,
    lastVerified: "2026-05-08",
    photoUrl: null,
  },
  {
    id: "m3",
    title: "Bratislava hlavná stanica",
    operator: "Slovnaft",
    address: "Predstaničné námestie 1",
    city: "Bratislava",
    country: "SK",
    lat: 48.1577,
    lng: 17.1061,
    status: "operational",
    usageType: "pay_at_location",
    connections: [
      { connectorType: "CCS2", powerKw: 50, voltageV: 400, ampereA: 125, currentType: "DC", quantity: 1 },
      { connectorType: "Type2", powerKw: 11, voltageV: 230, ampereA: 16, currentType: "AC", quantity: 2 },
    ],
    totalPoints: 3,
    maxPowerKw: 50,
    powerLevel: "dc_fast",
    costInfo: "0.42 €/kWh",
    openHours: "24/7",
    rating: 3.8,
    lastVerified: "2026-04-22",
    photoUrl: null,
  },
  {
    id: "m4",
    title: "IKEA Bratislava",
    operator: "ZSE Drive",
    address: "Ivanská cesta 18",
    city: "Bratislava",
    country: "SK",
    lat: 48.1701,
    lng: 17.1921,
    status: "operational",
    usageType: "public",
    connections: [
      { connectorType: "Type2", powerKw: 22, voltageV: 400, ampereA: 32, currentType: "AC", quantity: 6 },
    ],
    totalPoints: 6,
    maxPowerKw: 22,
    powerLevel: "ac_fast",
    costInfo: "Free while shopping",
    openHours: "09:00–21:00",
    rating: 4.6,
    lastVerified: "2026-05-15",
    photoUrl: null,
  },
  {
    id: "m5",
    title: "OMV Petržalka",
    operator: "OMV",
    address: "Panónska cesta 34",
    city: "Bratislava",
    country: "SK",
    lat: 48.1187,
    lng: 17.1213,
    status: "operational",
    usageType: "pay_at_location",
    connections: [
      { connectorType: "CCS2", powerKw: 150, voltageV: 800, ampereA: 187, currentType: "DC", quantity: 2 },
      { connectorType: "CCS2", powerKw: 50, voltageV: 400, ampereA: 125, currentType: "DC", quantity: 1 },
    ],
    totalPoints: 3,
    maxPowerKw: 150,
    powerLevel: "dc_ultra",
    costInfo: "0.45 €/kWh",
    openHours: "24/7",
    rating: 4.1,
    lastVerified: "2026-05-18",
    photoUrl: null,
  },
  {
    id: "m6",
    title: "Eurovea Tower Parking",
    operator: "GreenWay",
    address: "Pribinova 10",
    city: "Bratislava",
    country: "SK",
    lat: 48.1405,
    lng: 17.1192,
    status: "operational",
    usageType: "membership",
    connections: [
      { connectorType: "Type2", powerKw: 22, voltageV: 400, ampereA: 32, currentType: "AC", quantity: 8 },
      { connectorType: "CCS2", powerKw: 100, voltageV: 400, ampereA: 250, currentType: "DC", quantity: 2 },
    ],
    totalPoints: 10,
    maxPowerKw: 100,
    powerLevel: "dc_fast",
    costInfo: "0.29 €/kWh (members)",
    openHours: "24/7",
    rating: 4.7,
    lastVerified: "2026-05-20",
    photoUrl: null,
  },
  {
    id: "m7",
    title: "Tesla Supercharger — D1 Senec",
    operator: "Tesla",
    address: "Diaľnica D1, exit Senec",
    city: "Senec",
    country: "SK",
    lat: 48.2196,
    lng: 17.3894,
    status: "operational",
    usageType: "public",
    connections: [
      { connectorType: "Tesla", powerKw: 250, voltageV: 400, ampereA: 625, currentType: "DC", quantity: 12 },
      { connectorType: "CCS2", powerKw: 250, voltageV: 400, ampereA: 625, currentType: "DC", quantity: 4 },
    ],
    totalPoints: 16,
    maxPowerKw: 250,
    powerLevel: "dc_ultra",
    costInfo: "0.37 €/kWh",
    openHours: "24/7",
    rating: 4.8,
    lastVerified: "2026-05-21",
    photoUrl: null,
  },
  {
    id: "m8",
    title: "Kaufland Ružinov",
    operator: "Kaufland",
    address: "Ružinovská 1A",
    city: "Bratislava",
    country: "SK",
    lat: 48.1512,
    lng: 17.1634,
    status: "operational",
    usageType: "public",
    connections: [
      { connectorType: "Type2", powerKw: 22, voltageV: 400, ampereA: 32, currentType: "AC", quantity: 4 },
    ],
    totalPoints: 4,
    maxPowerKw: 22,
    powerLevel: "ac_fast",
    costInfo: "Free (2h limit)",
    openHours: "07:00–21:00",
    rating: 4.3,
    lastVerified: "2026-05-12",
    photoUrl: null,
  },
  {
    id: "m9",
    title: "MOL Zlaté piesky",
    operator: "MOL Plugee",
    address: "Vajnorská 100",
    city: "Bratislava",
    country: "SK",
    lat: 48.1782,
    lng: 17.1671,
    status: "temporarily_unavailable",
    usageType: "pay_at_location",
    connections: [
      { connectorType: "CCS2", powerKw: 75, voltageV: 400, ampereA: 187, currentType: "DC", quantity: 2 },
      { connectorType: "CHAdeMO", powerKw: 50, voltageV: 400, ampereA: 125, currentType: "DC", quantity: 1 },
    ],
    totalPoints: 3,
    maxPowerKw: 75,
    powerLevel: "dc_fast",
    costInfo: "0.49 €/kWh",
    openHours: "24/7",
    rating: 3.5,
    lastVerified: "2026-04-30",
    photoUrl: null,
  },
  {
    id: "m10",
    title: "Nivy Station Garage",
    operator: "ZSE Drive",
    address: "Mlynské nivy 16",
    city: "Bratislava",
    country: "SK",
    lat: 48.1469,
    lng: 17.1284,
    status: "operational",
    usageType: "public",
    connections: [
      { connectorType: "CCS2", powerKw: 100, voltageV: 400, ampereA: 250, currentType: "DC", quantity: 4 },
      { connectorType: "Type2", powerKw: 22, voltageV: 400, ampereA: 32, currentType: "AC", quantity: 8 },
    ],
    totalPoints: 12,
    maxPowerKw: 100,
    powerLevel: "dc_fast",
    costInfo: "0.35 €/kWh",
    openHours: "24/7",
    rating: 4.4,
    lastVerified: "2026-05-19",
    photoUrl: null,
  },
  {
    id: "m11",
    title: "Bratislava Airport P1",
    operator: "GreenWay",
    address: "Letisko M. R. Štefánika",
    city: "Bratislava",
    country: "SK",
    lat: 48.1702,
    lng: 17.2127,
    status: "operational",
    usageType: "pay_at_location",
    connections: [
      { connectorType: "CCS2", powerKw: 50, voltageV: 400, ampereA: 125, currentType: "DC", quantity: 2 },
      { connectorType: "Type2", powerKw: 11, voltageV: 230, ampereA: 16, currentType: "AC", quantity: 4 },
    ],
    totalPoints: 6,
    maxPowerKw: 50,
    powerLevel: "dc_fast",
    costInfo: "0.40 €/kWh",
    openHours: "24/7",
    rating: 3.9,
    lastVerified: "2026-05-05",
    photoUrl: null,
  },
  {
    id: "m12",
    title: "Lidl Dúbravka",
    operator: "Lidl",
    address: "Saratovská 8",
    city: "Bratislava",
    country: "SK",
    lat: 48.1868,
    lng: 17.0425,
    status: "planned",
    usageType: "public",
    connections: [
      { connectorType: "Type2", powerKw: 22, voltageV: 400, ampereA: 32, currentType: "AC", quantity: 4 },
      { connectorType: "CCS2", powerKw: 50, voltageV: 400, ampereA: 125, currentType: "DC", quantity: 1 },
    ],
    totalPoints: 5,
    maxPowerKw: 50,
    powerLevel: "dc_fast",
    costInfo: null,
    openHours: null,
    rating: null,
    lastVerified: null,
    photoUrl: null,
  },
  {
    id: "m13",
    title: "Trnava — City Park",
    operator: "ZSE Drive",
    address: "Kapitulská 1",
    city: "Trnava",
    country: "SK",
    lat: 48.3774,
    lng: 17.5877,
    status: "operational",
    usageType: "public",
    connections: [
      { connectorType: "CCS2", powerKw: 100, voltageV: 400, ampereA: 250, currentType: "DC", quantity: 2 },
      { connectorType: "Type2", powerKw: 22, voltageV: 400, ampereA: 32, currentType: "AC", quantity: 2 },
    ],
    totalPoints: 4,
    maxPowerKw: 100,
    powerLevel: "dc_fast",
    costInfo: "0.38 €/kWh",
    openHours: "24/7",
    rating: 4.0,
    lastVerified: "2026-05-14",
    photoUrl: null,
  },
  {
    id: "m14",
    title: "Nitra — Mlyny Shopping",
    operator: "GreenWay",
    address: "Štefánikova trieda 61",
    city: "Nitra",
    country: "SK",
    lat: 48.3085,
    lng: 18.0841,
    status: "operational",
    usageType: "public",
    connections: [
      { connectorType: "CCS2", powerKw: 60, voltageV: 400, ampereA: 150, currentType: "DC", quantity: 2 },
      { connectorType: "Type2", powerKw: 22, voltageV: 400, ampereA: 32, currentType: "AC", quantity: 3 },
    ],
    totalPoints: 5,
    maxPowerKw: 60,
    powerLevel: "dc_fast",
    costInfo: "0.36 €/kWh",
    openHours: "08:00–22:00",
    rating: 4.1,
    lastVerified: "2026-05-06",
    photoUrl: null,
  },
  {
    id: "m15",
    title: "Vienna — SCS Vösendorf",
    operator: "Wien Energie",
    address: "SCS-Straße 2",
    city: "Vösendorf",
    country: "AT",
    lat: 48.1297,
    lng: 16.3239,
    status: "operational",
    usageType: "public",
    connections: [
      { connectorType: "CCS2", powerKw: 300, voltageV: 800, ampereA: 375, currentType: "DC", quantity: 6 },
      { connectorType: "CCS2", powerKw: 150, voltageV: 400, ampereA: 375, currentType: "DC", quantity: 4 },
    ],
    totalPoints: 10,
    maxPowerKw: 300,
    powerLevel: "dc_ultra",
    costInfo: "0.41 €/kWh",
    openHours: "24/7",
    rating: 4.6,
    lastVerified: "2026-05-22",
    photoUrl: null,
  },
  // ─── GLOBAL: USA ─────────────────────────────────────────────────────
  { id: "g1", title: "Tesla Supercharger — Kettleman City", operator: "Tesla", address: "33550 Bernard Dr", city: "Kettleman City", country: "US", lat: 35.9894, lng: -119.9624, status: "operational", usageType: "public", connections: [{ connectorType: "Tesla", powerKw: 250, voltageV: 400, ampereA: 625, currentType: "DC", quantity: 40 }, { connectorType: "CCS2", powerKw: 250, voltageV: 400, ampereA: 625, currentType: "DC", quantity: 8 }], totalPoints: 48, maxPowerKw: 250, powerLevel: "dc_ultra", costInfo: "$0.38/kWh", openHours: "24/7", rating: 4.7, lastVerified: "2026-05-20", photoUrl: null },
  { id: "g2", title: "Electrify America — Manhattan, NY", operator: "Electrify America", address: "320 W 31st St", city: "New York", country: "US", lat: 40.7505, lng: -73.9967, status: "operational", usageType: "public", connections: [{ connectorType: "CCS2", powerKw: 350, voltageV: 800, ampereA: 437, currentType: "DC", quantity: 6 }, { connectorType: "CHAdeMO", powerKw: 50, voltageV: 400, ampereA: 125, currentType: "DC", quantity: 2 }], totalPoints: 8, maxPowerKw: 350, powerLevel: "dc_ultra", costInfo: "$0.43/kWh", openHours: "24/7", rating: 4.3, lastVerified: "2026-05-18", photoUrl: null },
  { id: "g3", title: "ChargePoint — LAX Airport", operator: "ChargePoint", address: "1 World Way", city: "Los Angeles", country: "US", lat: 33.9416, lng: -118.4085, status: "operational", usageType: "public", connections: [{ connectorType: "CCS2", powerKw: 62, voltageV: 400, ampereA: 155, currentType: "DC", quantity: 8 }, { connectorType: "Type2", powerKw: 22, voltageV: 400, ampereA: 32, currentType: "AC", quantity: 20 }], totalPoints: 28, maxPowerKw: 62, powerLevel: "dc_fast", costInfo: "$0.35/kWh", openHours: "24/7", rating: 4.1, lastVerified: "2026-05-15", photoUrl: null },
  // ─── GLOBAL: CHINA ───────────────────────────────────────────────────
  { id: "g4", title: "NIO Power Swap — Beijing Chaoyang", operator: "NIO", address: "Chaoyang District", city: "Beijing", country: "CN", lat: 39.9219, lng: 116.4435, status: "operational", usageType: "public", connections: [{ connectorType: "GB/T", powerKw: 180, voltageV: 400, ampereA: 450, currentType: "DC", quantity: 4 }], totalPoints: 4, maxPowerKw: 180, powerLevel: "dc_ultra", costInfo: "¥1.20/kWh", openHours: "24/7", rating: 4.8, lastVerified: "2026-05-21", photoUrl: null },
  { id: "g5", title: "State Grid — Shanghai Pudong", operator: "State Grid", address: "Lujiazui Ring Road", city: "Shanghai", country: "CN", lat: 31.2357, lng: 121.5018, status: "operational", usageType: "public", connections: [{ connectorType: "GB/T", powerKw: 120, voltageV: 400, ampereA: 300, currentType: "DC", quantity: 20 }, { connectorType: "Type2", powerKw: 7, voltageV: 230, ampereA: 32, currentType: "AC", quantity: 40 }], totalPoints: 60, maxPowerKw: 120, powerLevel: "dc_fast", costInfo: "¥0.85/kWh", openHours: "24/7", rating: 4.2, lastVerified: "2026-05-19", photoUrl: null },
  // ─── GLOBAL: JAPAN ───────────────────────────────────────────────────
  { id: "g6", title: "CHAdeMO Hub — Shinjuku", operator: "TEPCO", address: "Shinjuku Station West", city: "Tokyo", country: "JP", lat: 35.6896, lng: 139.6922, status: "operational", usageType: "public", connections: [{ connectorType: "CHAdeMO", powerKw: 90, voltageV: 400, ampereA: 225, currentType: "DC", quantity: 6 }, { connectorType: "Type2", powerKw: 22, voltageV: 400, ampereA: 32, currentType: "AC", quantity: 4 }], totalPoints: 10, maxPowerKw: 90, powerLevel: "dc_fast", costInfo: "¥44/min", openHours: "05:00–24:00", rating: 4.5, lastVerified: "2026-05-17", photoUrl: null },
  // ─── GLOBAL: SOUTH KOREA ─────────────────────────────────────────────
  { id: "g7", title: "Hyundai E-pit — Gangnam", operator: "Hyundai", address: "Gangnam-daero 396", city: "Seoul", country: "KR", lat: 37.4979, lng: 127.0276, status: "operational", usageType: "public", connections: [{ connectorType: "CCS2", powerKw: 350, voltageV: 800, ampereA: 437, currentType: "DC", quantity: 8 }], totalPoints: 8, maxPowerKw: 350, powerLevel: "dc_ultra", costInfo: "₩292/kWh", openHours: "24/7", rating: 4.6, lastVerified: "2026-05-22", photoUrl: null },
  // ─── GLOBAL: INDIA ───────────────────────────────────────────────────
  { id: "g8", title: "Tata Power — Mumbai BKC", operator: "Tata Power", address: "Bandra-Kurla Complex", city: "Mumbai", country: "IN", lat: 19.0655, lng: 72.8675, status: "operational", usageType: "public", connections: [{ connectorType: "CCS2", powerKw: 60, voltageV: 400, ampereA: 150, currentType: "DC", quantity: 4 }, { connectorType: "Type2", powerKw: 22, voltageV: 400, ampereA: 32, currentType: "AC", quantity: 6 }], totalPoints: 10, maxPowerKw: 60, powerLevel: "dc_fast", costInfo: "₹18/kWh", openHours: "24/7", rating: 4.0, lastVerified: "2026-05-14", photoUrl: null },
  // ─── GLOBAL: UAE ─────────────────────────────────────────────────────
  { id: "g9", title: "DEWA EV Green Charger — Dubai Mall", operator: "DEWA", address: "Financial Center Rd", city: "Dubai", country: "AE", lat: 25.1972, lng: 55.2744, status: "operational", usageType: "public", connections: [{ connectorType: "CCS2", powerKw: 150, voltageV: 400, ampereA: 375, currentType: "DC", quantity: 6 }, { connectorType: "Type2", powerKw: 22, voltageV: 400, ampereA: 32, currentType: "AC", quantity: 10 }], totalPoints: 16, maxPowerKw: 150, powerLevel: "dc_ultra", costInfo: "Free (DEWA)", openHours: "24/7", rating: 4.7, lastVerified: "2026-05-20", photoUrl: null },
  // ─── GLOBAL: UK ──────────────────────────────────────────────────────
  { id: "g10", title: "BP Pulse — London Canary Wharf", operator: "BP Pulse", address: "Jubilee Place", city: "London", country: "GB", lat: 51.5052, lng: -0.0187, status: "operational", usageType: "public", connections: [{ connectorType: "CCS2", powerKw: 150, voltageV: 400, ampereA: 375, currentType: "DC", quantity: 8 }, { connectorType: "Type2", powerKw: 22, voltageV: 400, ampereA: 32, currentType: "AC", quantity: 12 }], totalPoints: 20, maxPowerKw: 150, powerLevel: "dc_ultra", costInfo: "£0.65/kWh", openHours: "24/7", rating: 4.2, lastVerified: "2026-05-18", photoUrl: null },
  // ─── GLOBAL: GERMANY ─────────────────────────────────────────────────
  { id: "g11", title: "IONITY — Autobahn A9 Himmelkron", operator: "IONITY", address: "Rastplatz Himmelkron-Ost, A9", city: "Himmelkron", country: "DE", lat: 50.0698, lng: 11.5954, status: "operational", usageType: "public", connections: [{ connectorType: "CCS2", powerKw: 350, voltageV: 800, ampereA: 437, currentType: "DC", quantity: 12 }], totalPoints: 12, maxPowerKw: 350, powerLevel: "dc_ultra", costInfo: "€0.79/kWh (ad hoc)", openHours: "24/7", rating: 4.4, lastVerified: "2026-05-21", photoUrl: null },
  { id: "g12", title: "EnBW HyperHub — Berlin Alexanderplatz", operator: "EnBW", address: "Karl-Liebknecht-Str. 5", city: "Berlin", country: "DE", lat: 52.5219, lng: 13.4132, status: "operational", usageType: "public", connections: [{ connectorType: "CCS2", powerKw: 300, voltageV: 800, ampereA: 375, currentType: "DC", quantity: 20 }], totalPoints: 20, maxPowerKw: 300, powerLevel: "dc_ultra", costInfo: "€0.49/kWh", openHours: "24/7", rating: 4.6, lastVerified: "2026-05-22", photoUrl: null },
  // ─── GLOBAL: FRANCE ──────────────────────────────────────────────────
  { id: "g13", title: "TotalEnergies — Paris La Défense", operator: "TotalEnergies", address: "Parvis de La Défense", city: "Paris", country: "FR", lat: 48.8920, lng: 2.2360, status: "operational", usageType: "public", connections: [{ connectorType: "CCS2", powerKw: 175, voltageV: 400, ampereA: 437, currentType: "DC", quantity: 10 }, { connectorType: "Type2", powerKw: 22, voltageV: 400, ampereA: 32, currentType: "AC", quantity: 8 }], totalPoints: 18, maxPowerKw: 175, powerLevel: "dc_ultra", costInfo: "€0.52/kWh", openHours: "24/7", rating: 4.3, lastVerified: "2026-05-19", photoUrl: null },
  // ─── GLOBAL: NORWAY ──────────────────────────────────────────────────
  { id: "g14", title: "Circle K — Oslo Sentrum", operator: "Circle K / Mer", address: "Storgata 28", city: "Oslo", country: "NO", lat: 59.9145, lng: 10.7540, status: "operational", usageType: "public", connections: [{ connectorType: "CCS2", powerKw: 150, voltageV: 400, ampereA: 375, currentType: "DC", quantity: 6 }, { connectorType: "Type2", powerKw: 22, voltageV: 400, ampereA: 32, currentType: "AC", quantity: 4 }], totalPoints: 10, maxPowerKw: 150, powerLevel: "dc_ultra", costInfo: "NOK 5.49/kWh", openHours: "24/7", rating: 4.4, lastVerified: "2026-05-20", photoUrl: null },
  // ─── GLOBAL: AUSTRALIA ───────────────────────────────────────────────
  { id: "g15", title: "Chargefox — Sydney Olympic Park", operator: "Chargefox", address: "Olympic Blvd", city: "Sydney", country: "AU", lat: -33.8469, lng: 151.0695, status: "operational", usageType: "public", connections: [{ connectorType: "CCS2", powerKw: 350, voltageV: 800, ampereA: 437, currentType: "DC", quantity: 6 }], totalPoints: 6, maxPowerKw: 350, powerLevel: "dc_ultra", costInfo: "A$0.60/kWh", openHours: "24/7", rating: 4.5, lastVerified: "2026-05-16", photoUrl: null },
  // ─── GLOBAL: BRAZIL ──────────────────────────────────────────────────
  { id: "g16", title: "Tupinambá Energia — São Paulo Faria Lima", operator: "Tupinambá", address: "Av. Faria Lima 3000", city: "São Paulo", country: "BR", lat: -23.5815, lng: -46.6848, status: "operational", usageType: "public", connections: [{ connectorType: "CCS2", powerKw: 150, voltageV: 400, ampereA: 375, currentType: "DC", quantity: 4 }, { connectorType: "Type2", powerKw: 22, voltageV: 400, ampereA: 32, currentType: "AC", quantity: 8 }], totalPoints: 12, maxPowerKw: 150, powerLevel: "dc_ultra", costInfo: "R$2.10/kWh", openHours: "24/7", rating: 4.1, lastVerified: "2026-05-13", photoUrl: null },
  // ─── GLOBAL: SOUTH AFRICA ────────────────────────────────────────────
  { id: "g17", title: "GridCars — Johannesburg Sandton", operator: "GridCars", address: "Sandton City Mall", city: "Johannesburg", country: "ZA", lat: -26.1076, lng: 28.0567, status: "operational", usageType: "public", connections: [{ connectorType: "CCS2", powerKw: 60, voltageV: 400, ampereA: 150, currentType: "DC", quantity: 4 }, { connectorType: "Type2", powerKw: 22, voltageV: 400, ampereA: 32, currentType: "AC", quantity: 6 }], totalPoints: 10, maxPowerKw: 60, powerLevel: "dc_fast", costInfo: "R8.50/kWh", openHours: "06:00–22:00", rating: 3.9, lastVerified: "2026-05-10", photoUrl: null },
  // ─── GLOBAL: TURKEY ──────────────────────────────────────────────────
  { id: "g18", title: "ZES — Istanbul Levent", operator: "ZES (Zorlu)", address: "Büyükdere Cad.", city: "Istanbul", country: "TR", lat: 41.0802, lng: 29.0115, status: "operational", usageType: "public", connections: [{ connectorType: "CCS2", powerKw: 180, voltageV: 400, ampereA: 450, currentType: "DC", quantity: 4 }, { connectorType: "Type2", powerKw: 22, voltageV: 400, ampereA: 32, currentType: "AC", quantity: 6 }], totalPoints: 10, maxPowerKw: 180, powerLevel: "dc_ultra", costInfo: "₺8.20/kWh", openHours: "24/7", rating: 4.3, lastVerified: "2026-05-18", photoUrl: null },
  // ─── GLOBAL: SAUDI ARABIA ────────────────────────────────────────────
  { id: "g19", title: "Electromin — Riyadh King Fahd Rd", operator: "Electromin", address: "King Fahd Road", city: "Riyadh", country: "SA", lat: 24.7136, lng: 46.6753, status: "operational", usageType: "public", connections: [{ connectorType: "CCS2", powerKw: 200, voltageV: 400, ampereA: 500, currentType: "DC", quantity: 6 }], totalPoints: 6, maxPowerKw: 200, powerLevel: "dc_ultra", costInfo: "SAR 0.75/kWh", openHours: "24/7", rating: 4.4, lastVerified: "2026-05-19", photoUrl: null },
  // ─── GLOBAL: THAILAND ────────────────────────────────────────────────
  { id: "g20", title: "EA Anywhere — Bangkok Siam", operator: "Energy Absolute", address: "Siam Square One", city: "Bangkok", country: "TH", lat: 13.7450, lng: 100.5340, status: "operational", usageType: "public", connections: [{ connectorType: "CCS2", powerKw: 150, voltageV: 400, ampereA: 375, currentType: "DC", quantity: 4 }, { connectorType: "Type2", powerKw: 22, voltageV: 400, ampereA: 32, currentType: "AC", quantity: 4 }], totalPoints: 8, maxPowerKw: 150, powerLevel: "dc_ultra", costInfo: "฿7.50/kWh", openHours: "24/7", rating: 4.5, lastVerified: "2026-05-17", photoUrl: null },
  // ─── GLOBAL: MEXICO ──────────────────────────────────────────────────
  { id: "g21", title: "Tesla Supercharger — CDMX Santa Fe", operator: "Tesla", address: "Centro Santa Fe", city: "Ciudad de México", country: "MX", lat: 19.3598, lng: -99.2769, status: "operational", usageType: "public", connections: [{ connectorType: "Tesla", powerKw: 250, voltageV: 400, ampereA: 625, currentType: "DC", quantity: 12 }, { connectorType: "CCS2", powerKw: 250, voltageV: 400, ampereA: 625, currentType: "DC", quantity: 4 }], totalPoints: 16, maxPowerKw: 250, powerLevel: "dc_ultra", costInfo: "MXN 5.90/kWh", openHours: "24/7", rating: 4.5, lastVerified: "2026-05-15", photoUrl: null },
  // ─── GLOBAL: CANADA ──────────────────────────────────────────────────
  { id: "g22", title: "Petro-Canada — Toronto Yorkdale", operator: "Petro-Canada", address: "3401 Dufferin St", city: "Toronto", country: "CA", lat: 43.7254, lng: -79.4522, status: "operational", usageType: "public", connections: [{ connectorType: "CCS2", powerKw: 200, voltageV: 400, ampereA: 500, currentType: "DC", quantity: 8 }], totalPoints: 8, maxPowerKw: 200, powerLevel: "dc_ultra", costInfo: "C$0.48/kWh", openHours: "24/7", rating: 4.3, lastVerified: "2026-05-18", photoUrl: null },
  // ─── GLOBAL: KAZAKHSTAN ──────────────────────────────────────────────
  { id: "g23", title: "AQNIET Charge — Astana Expo", operator: "AQNIET", address: "Expo Boulevard", city: "Astana", country: "KZ", lat: 51.0899, lng: 71.4168, status: "operational", usageType: "public", connections: [{ connectorType: "CCS2", powerKw: 60, voltageV: 400, ampereA: 150, currentType: "DC", quantity: 4 }, { connectorType: "Type2", powerKw: 22, voltageV: 400, ampereA: 32, currentType: "AC", quantity: 4 }], totalPoints: 8, maxPowerKw: 60, powerLevel: "dc_fast", costInfo: "₸50/kWh", openHours: "24/7", rating: 4.0, lastVerified: "2026-05-12", photoUrl: null },
  // ─── GLOBAL: UZBEKISTAN ──────────────────────────────────────────────
  { id: "g24", title: "UzCharge — Tashkent City", operator: "UzCharge", address: "Tashkent City Mall", city: "Tashkent", country: "UZ", lat: 41.3117, lng: 69.2797, status: "operational", usageType: "public", connections: [{ connectorType: "CCS2", powerKw: 60, voltageV: 400, ampereA: 150, currentType: "DC", quantity: 2 }, { connectorType: "Type2", powerKw: 22, voltageV: 400, ampereA: 32, currentType: "AC", quantity: 4 }], totalPoints: 6, maxPowerKw: 60, powerLevel: "dc_fast", costInfo: "2500 сум/kWh", openHours: "08:00–22:00", rating: 3.8, lastVerified: "2026-05-08", photoUrl: null },
  // ─── GLOBAL: GEORGIA ─────────────────────────────────────────────────
  { id: "g25", title: "EV Point — Tbilisi Vake", operator: "EV Point Georgia", address: "Chavchavadze Ave 37", city: "Tbilisi", country: "GE", lat: 41.7086, lng: 44.7681, status: "operational", usageType: "public", connections: [{ connectorType: "CCS2", powerKw: 50, voltageV: 400, ampereA: 125, currentType: "DC", quantity: 2 }, { connectorType: "Type2", powerKw: 22, voltageV: 400, ampereA: 32, currentType: "AC", quantity: 4 }], totalPoints: 6, maxPowerKw: 50, powerLevel: "dc_fast", costInfo: "0.30 GEL/kWh", openHours: "24/7", rating: 4.1, lastVerified: "2026-05-11", photoUrl: null },
];
