import type { ProducerProfile } from "./producers";

export const PRODUCER_PROFILES: Record<string, ProducerProfile> = {
  // ─── SOLAR ENERGY PRODUCERS ────────────────────────────────────────────
  "jinko-solar-haining": {
    description: "One of the world's largest solar module manufacturers, producing high-efficiency monocrystalline panels using N-type TOPCon technology. Listed on NYSE and Shanghai SSE.",
    founded: 2006,
    employees: "~40,000",
    website: "https://www.jinkosolar.com",
    email: "sales@jinkosolar.com",
    phone: "+86-573-8439-8028",
    address: "1 Jingke Road, Shangrao Economic Development Zone, Jiangxi Province, China",
    ceo: "Xiande Li",
    stockTicker: "JKS (NYSE)",
    certifications: ["IEC 61215", "IEC 61730", "UL 1703", "ISO 9001", "ISO 14001"],
    keyProducts: ["Tiger Neo N-type modules", "Tiger Pro P-type modules", "Suntank residential storage", "Jinko EaglePerc panels"],
  },
  "trina-solar-changzhou": {
    description: "Global leader in photovoltaic modules and smart energy solutions. Pioneer in 210mm Vertex series with over 150 GW shipped worldwide.",
    founded: 1997,
    employees: "~50,000",
    website: "https://www.trinasolar.com",
    email: "sales@trinasolar.com",
    phone: "+86-519-8548-2008",
    address: "No. 2 Trina Road, Trina PV Park, Changzhou, Jiangsu 213031, China",
    ceo: "Gao Jifan",
    stockTicker: "688599 (SSE STAR)",
    certifications: ["IEC 61215/61730", "UL 61730", "ISO 9001/14001/45001", "TÜV Rheinland"],
    keyProducts: ["Vertex S+ residential modules", "Vertex N utility modules", "TrinaTracker Vanguard", "Trina Storage Elementa"],
  },
  "longi-green-xian": {
    description: "World's largest solar wafer and module manufacturer by capacity. Pioneered monocrystalline PERC and HPC (Hybrid Passivated Contact) technology.",
    founded: 2000,
    employees: "~60,000",
    website: "https://www.longi.com",
    email: "sales@longi.com",
    phone: "+86-29-6127-5888",
    address: "No. 388 Hangtian Middle Road, Xi'an, Shaanxi 710100, China",
    ceo: "Zhong Baoshen",
    stockTicker: "601012 (SSE)",
    certifications: ["IEC 61215/61730", "TÜV Rheinland", "ISO 9001/14001", "Science Based Targets (SBTi)"],
    keyProducts: ["Hi-MO 7 / Hi-MO X6 modules", "LONGi Blade hydrogen electrolyzer", "LONGi HPBC cells", "LONGi monocrystalline wafers"],
  },
  "canadian-solar-guelph": {
    description: "Vertically integrated solar company with operations spanning ingots, wafers, cells, modules, and utility-scale project development across 6 continents.",
    founded: 2001,
    employees: "~22,000",
    website: "https://www.canadiansolar.com",
    email: "inquire@canadiansolar.com",
    phone: "+1-519-837-1881",
    address: "545 Speedvale Avenue West, Guelph, Ontario N1K 1E6, Canada",
    ceo: "Shawn Qu",
    stockTicker: "CSIQ (NASDAQ)",
    certifications: ["UL 61730", "IEC 61215", "ISO 9001/14001", "IEC 62941"],
    keyProducts: ["HiKu7 high-power modules", "BiHiKu7 bifacial modules", "EP Cube residential storage", "SolBank utility BESS"],
  },
  "first-solar-tempe": {
    description: "America's largest solar manufacturer, unique in using CdTe thin-film technology instead of crystalline silicon. Low carbon footprint per watt.",
    founded: 1999,
    employees: "~7,000",
    website: "https://www.firstsolar.com",
    email: "info@firstsolar.com",
    phone: "+1-602-414-9300",
    address: "350 W Washington Street, Suite 600, Tempe, AZ 85281, USA",
    ceo: "Mark Widmar",
    stockTicker: "FSLR (NASDAQ)",
    certifications: ["UL 61730", "IEC 61215", "ISO 9001/14001/45001", "Cradle to Cradle Certified"],
    keyProducts: ["Series 7 CdTe utility modules", "Series 6 Plus thin-film modules", "CuRe technology (recyclable)", "EPC services"],
  },
  "hanwha-qcells-seoul": {
    description: "South Korean solar cell and module manufacturer, subsidiary of Hanwha Group. Pioneered Q.ANTUM PERC technology with cells exceeding 23% efficiency.",
    founded: 1999,
    employees: "~10,000",
    website: "https://www.qcells.com",
    email: "info@qcells.com",
    phone: "+82-2-729-2700",
    address: "86 Cheonggyecheon-ro, Jung-gu, Seoul, South Korea",
    ceo: "Justin Lee",
    stockTicker: "Part of Hanwha Solutions (009830.KS)",
    certifications: ["IEC 61215/61730", "UL 1703", "ISO 9001", "TÜV Nord"],
    keyProducts: ["Q.PEAK DUO residential panels", "Q.TRON TOPCon modules", "Q.HOME Core storage", "Q.FLAT rooftop systems"],
  },
  "ja-solar-beijing": {
    description: "One of the largest PV manufacturers globally with over 100 GW of modules shipped. Strong in both utility and distributed generation markets.",
    founded: 2005,
    employees: "~35,000",
    website: "https://www.jasolar.com",
    email: "sales@jasolar.com",
    phone: "+86-10-6361-0055",
    address: "16 Lize Middle Road, Fengtai District, Beijing 100073, China",
    ceo: "Jin Baofang",
    stockTicker: "002459 (SZSE)",
    certifications: ["IEC 61215/61730", "TÜV SÜD", "UL 61730", "ISO 9001/14001"],
    keyProducts: ["DeepBlue 4.0 N-type modules", "DeepBlue 3.0 bifacial", "JAM residential panels", "SmartPV tracking solutions"],
  },
  "risen-energy-ninghai": {
    description: "Chinese solar manufacturer specializing in heterojunction (HJT) and TOPCon modules. Known for aggressive R&D in next-gen cell technology.",
    founded: 1986,
    employees: "~18,000",
    website: "https://www.risenenergy.com",
    email: "sales@risenenergy.com",
    phone: "+86-574-6578-6800",
    address: "No. 1 Fuchun Road, Ninghai County, Ningbo, Zhejiang, China",
    ceo: "Xie Jian",
    stockTicker: "300118 (SZSE ChiNext)",
    certifications: ["IEC 61215/61730", "TÜV Rheinland", "ISO 9001/14001", "CQC"],
    keyProducts: ["Hyper-ion HJT modules", "Titan M series N-type", "RSM residential panels", "Utility-scale EPC"],
  },
  "sunpower-san-jose": {
    description: "Premium residential solar manufacturer known for the industry's highest-efficiency panels (22.8%+). Now focused exclusively on residential market.",
    founded: 1985,
    employees: "~3,500",
    website: "https://www.sunpower.com",
    email: "support@sunpower.com",
    phone: "+1-800-786-7693",
    address: "51 Rio Robles, San Jose, CA 95134, USA",
    ceo: "Peter Faricy",
    stockTicker: "SPWR (NASDAQ)",
    certifications: ["UL 1703", "IEC 61215", "ISO 9001", "Cradle to Cradle Bronze"],
    keyProducts: ["Maxeon Gen 7 panels", "SunVault residential battery", "SunPower One platform", "EnergyLink monitoring"],
  },
  "rec-group-singapore": {
    description: "Norwegian-founded, Singapore-headquartered solar panel manufacturer known for high quality and patented split-cell technology with 25-year product warranty.",
    founded: 1996,
    employees: "~2,500",
    website: "https://www.recgroup.com",
    email: "info@recgroup.com",
    phone: "+65-6829-4200",
    address: "20 Tuas South Avenue 14, Singapore 637312",
    ceo: "Jan Enno Bicker",
    certifications: ["IEC 61215/61730", "UL 1703", "ISO 9001/14001", "Cradle to Cradle"],
    keyProducts: ["TwinPeak 5 Series panels", "Alpha Pure-R residential", "REC ProTrust warranty", "RECview monitoring"],
  },
  "maxeon-solar-sg": {
    description: "Spin-off from SunPower focused on premium IBC (Interdigitated Back Contact) solar cells. Holds world record for silicon solar cell efficiency.",
    founded: 2020,
    employees: "~5,000",
    website: "https://www.maxeon.com",
    email: "info@maxeon.com",
    phone: "+65-6338-1888",
    address: "8 Marina Boulevard, Marina Bay Financial Centre, Singapore 018981",
    ceo: "Bill Mulligan",
    stockTicker: "MAXN (NASDAQ)",
    certifications: ["IEC 61215/61730", "UL 61730", "ISO 9001/14001", "TÜV Rheinland"],
    keyProducts: ["Maxeon 7 IBC cells", "Performance line panels", "SunPower branded residential", "AC modules"],
  },
  "enel-green-power-rome": {
    description: "Renewable energy division of Enel Group, one of Italy's largest utilities. Operates wind, solar, hydro, and geothermal plants across 5 continents.",
    founded: 2008,
    employees: "~7,500",
    website: "https://www.enelgreenpower.com",
    email: "info@enelgreenpower.com",
    phone: "+39-06-8305-1",
    address: "Viale Regina Margherita 137, 00198 Roma, Italy",
    ceo: "Salvatore Bernabei",
    stockTicker: "Part of Enel (ENEL.MI)",
    certifications: ["ISO 9001/14001/45001", "SA8000", "EMAS", "GRI Standards"],
    keyProducts: ["Utility-scale solar farms", "Onshore wind parks", "Hybrid renewable plants", "Green hydrogen"],
  },
  "adani-solar-ahmedabad": {
    description: "Part of Adani Group, India's largest solar power producer. Operates the world's largest single-site solar farm (Khavda, Gujarat) with 30 GW planned.",
    founded: 2015,
    employees: "~5,000",
    website: "https://www.adanigreenenergy.com",
    email: "info@adanigreen.com",
    phone: "+91-79-2656-5555",
    address: "Adani House, Nr. Mithakhali Six Roads, Navrangpura, Ahmedabad 380009, India",
    ceo: "Vneet S. Jaain",
    stockTicker: "ADANIGREEN (NSE)",
    certifications: ["ISO 9001/14001/45001", "IEC 61215/61730", "BIS certified"],
    keyProducts: ["Utility-scale solar parks", "Solar cell manufacturing", "Wind-solar hybrid farms", "Green hydrogen"],
  },
  "enphase-energy-fremont": {
    description: "Pioneer and global leader in microinverter technology. Each solar panel gets its own inverter, maximizing output and enabling panel-level monitoring.",
    founded: 2006,
    employees: "~3,500",
    website: "https://www.enphase.com",
    email: "info@enphaseenergy.com",
    phone: "+1-877-797-4743",
    address: "47281 Bayside Pkwy, Fremont, CA 94538, USA",
    ceo: "Badri Kothandaraman",
    stockTicker: "ENPH (NASDAQ)",
    certifications: ["UL 1741/1741 SA", "IEEE 1547", "IEC 62109", "ISO 9001"],
    keyProducts: ["IQ8 microinverters", "IQ Battery 5P/10T", "Enphase Energy System", "Enlighten monitoring"],
  },
  "solaredge-herzliya": {
    description: "Israeli company that invented the DC power optimizer concept, enabling panel-level MPPT and safety shutdown. Market leader in residential string inverters.",
    founded: 2006,
    employees: "~5,000",
    website: "https://www.solaredge.com",
    email: "info@solaredge.com",
    phone: "+972-9-957-6620",
    address: "1 HaMada Street, Herzliya 4673335, Israel",
    ceo: "Zvi Lando",
    stockTicker: "SEDG (NASDAQ)",
    certifications: ["IEC 62109", "UL 1741 SA", "IEEE 1547", "ISO 9001/14001"],
    keyProducts: ["SolarEdge Home inverters", "Power Optimizers P-series", "Home Battery 400V", "SolarEdge ONE AI platform"],
  },
  // ─── WIND ENERGY PRODUCERS ─────────────────────────────────────────────
  "vestas-aarhus": {
    description: "World's largest wind turbine manufacturer by installed capacity (182+ GW). Danish company with turbines in 88 countries. Pioneer of V236-15.0 MW offshore platform.",
    founded: 1945,
    employees: "~29,000",
    website: "https://www.vestas.com",
    email: "vestas@vestas.com",
    phone: "+45-9730-0000",
    address: "Hedeager 42, 8200 Aarhus N, Denmark",
    ceo: "Henrik Andersen",
    stockTicker: "VWS.CO (Copenhagen)",
    certifications: ["IEC 61400", "ISO 9001/14001/45001", "OHSAS 18001", "DNV Type Certificate"],
    keyProducts: ["V236-15.0 MW offshore", "V162-6.2 MW onshore", "V150-6.0 MW", "EnVentus platform"],
  },
  "siemens-gamesa-bilbao": {
    description: "Part of Siemens Energy, one of the world's top wind turbine OEMs. Leader in offshore wind with the SG 14-236 DD platform (world's largest turbine).",
    founded: 2017,
    employees: "~27,000",
    website: "https://www.siemensgamesa.com",
    email: "info@siemensgamesa.com",
    phone: "+34-944-403-000",
    address: "Parque Tecnológico de Bizkaia, Edificio 222, 48170 Zamudio, Spain",
    ceo: "Jochen Eickholt",
    stockTicker: "Part of Siemens Energy (ENR.DE)",
    certifications: ["IEC 61400", "DNV GL", "ISO 9001/14001/45001", "IECRE"],
    keyProducts: ["SG 14-236 DD offshore (14 MW)", "SG 6.6-170 onshore", "SG 5.0-145 onshore", "Gamesa digital services"],
  },
  "goldwind-urumqi": {
    description: "China's largest and world's second-largest wind turbine manufacturer. Pioneer in permanent magnet direct drive (PMDD) technology, eliminating gearbox failures.",
    founded: 1998,
    employees: "~11,000",
    website: "https://www.goldwind.com",
    email: "overseas@goldwind.com.cn",
    phone: "+86-991-380-0888",
    address: "No. 107 Shanghai Road, Ürümqi Economic Development Zone, Xinjiang 830026, China",
    ceo: "Cao Zhigang",
    stockTicker: "002202 (SZSE) / 2208.HK",
    certifications: ["IEC 61400-22", "GL 2010", "ISO 9001/14001", "IECRE"],
    keyProducts: ["GWH 252-16.0 MW offshore", "GW 185-8.0 MW onshore", "GW 155-4.5 MW", "PMDD technology platform"],
  },
  "ge-renewable-paris": {
    description: "Wind energy division of GE Vernova. Manufactures the Haliade-X, one of the most powerful offshore turbines. Presence in 40+ countries.",
    founded: 2015,
    employees: "~40,000",
    website: "https://www.gevernova.com/wind",
    email: "wind.info@ge.com",
    phone: "+33-1-4295-0000",
    address: "61 Avenue de la Grande Armée, 75016 Paris, France",
    ceo: "Scott Strazik (GE Vernova CEO)",
    stockTicker: "GEV (NYSE)",
    certifications: ["IEC 61400", "DNV GL", "ISO 9001/14001", "IECRE"],
    keyProducts: ["Haliade-X 14.7 MW offshore", "Cypress onshore 5.5 MW", "Sierra compact midrange", "LM Wind Power blades"],
  },
  "nordex-hamburg": {
    description: "German-Spanish wind turbine manufacturer focused on onshore wind. Known for the Delta4000 platform with rotors up to 175m. Strong in European and LatAm markets.",
    founded: 1985,
    employees: "~10,300",
    website: "https://www.nordex-online.com",
    email: "info@nordex-online.com",
    phone: "+49-40-3004-7100",
    address: "Langenhorner Chaussee 600, 22419 Hamburg, Germany",
    ceo: "José Luis Blanco",
    stockTicker: "NDX1 (XETRA)",
    certifications: ["IEC 61400", "DNV GL", "ISO 9001/14001/45001", "IECRE"],
    keyProducts: ["N175/6.X Delta4000", "N163/5.X onshore", "N149/5.X cold climate", "Nordex SCADA"],
  },
  "enercon-aurich": {
    description: "German privately-held wind turbine manufacturer, unique in using gearless direct-drive technology since 1993. All manufacturing in Germany.",
    founded: 1984,
    employees: "~14,000",
    website: "https://www.enercon.de",
    email: "info@enercon.de",
    phone: "+49-4941-927-0",
    address: "Dreekamp 5, 26605 Aurich, Germany",
    ceo: "Momme Janssen",
    certifications: ["IEC 61400", "DIBt", "ISO 9001/14001/50001", "GL 2010"],
    keyProducts: ["E-175 EP5 (5.5 MW)", "E-160 EP5 onshore", "E-138 EP3 E3 onshore", "ENERCON Storm Control"],
  },
  "orsted-fredericia": {
    description: "World's largest offshore wind developer (formerly DONG Energy). Operates major offshore farms including Hornsea in UK and Revolution Wind in US.",
    founded: 1972,
    employees: "~8,000",
    website: "https://www.orsted.com",
    email: "info@orsted.com",
    phone: "+45-9955-1111",
    address: "Kraftværksvej 53, 7000 Fredericia, Denmark",
    ceo: "Mads Nipper",
    stockTicker: "ORSTED.CO (Copenhagen)",
    certifications: ["ISO 9001/14001/45001", "OHSAS 18001", "SBTi Net-Zero", "CDP A-list"],
    keyProducts: ["Offshore wind farms (15+ GW)", "Onshore wind", "Solar PV projects", "Green hydrogen (H2)"],
  },
  "suzlon-pune": {
    description: "India's largest wind turbine manufacturer and one of the pioneers of wind energy in Asia. Operates in 17 countries with 20+ GW installed.",
    founded: 1995,
    employees: "~7,000",
    website: "https://www.suzlon.com",
    email: "info@suzlon.com",
    phone: "+91-20-6702-2000",
    address: "One Earth, Hadapsar, Pune 411028, India",
    ceo: "JP Chalasani",
    stockTicker: "SUZLON (NSE)",
    certifications: ["IEC 61400", "ISO 9001/14001/45001", "IECRE", "BIS"],
    keyProducts: ["S144-3.15 MW onshore", "S120-2.1 MW", "S128-2.6 MW hybrid", "O&M services"],
  },
  "mingyang-zhongshan": {
    description: "China's leading offshore wind manufacturer and one of the world's top 5. Developed world's largest typhoon-resistant floating turbine (OceanX 16.6 MW).",
    founded: 2006,
    employees: "~6,000",
    website: "https://www.myse.com.cn",
    email: "overseas@myse.com.cn",
    phone: "+86-760-2829-5666",
    address: "No. 8 Gangkou Road, Zhongshan, Guangdong 528400, China",
    ceo: "Zhang Chuanwei",
    stockTicker: "601615 (SSE)",
    certifications: ["IEC 61400", "DNV GL", "ISO 9001/14001/45001", "CCS"],
    keyProducts: ["MySE 16.6-260 offshore", "OceanX floating platform", "MySE 8.X-216 semi-offshore", "MySE 6.25-182 onshore"],
  },
  "envision-energy-shanghai": {
    description: "Chinese green-tech company combining wind turbines, batteries, and AIoT software (EnOS platform). Self-proclaimed 'technology company' rather than just turbine maker.",
    founded: 2007,
    employees: "~7,000",
    website: "https://www.envision-group.com",
    email: "contact@envision-group.com",
    phone: "+86-21-3859-1500",
    address: "No. 2 Fengxian East Road, Shanghai 200000, China",
    ceo: "Lei Zhang",
    certifications: ["IEC 61400", "ISO 9001/14001", "DNV GL", "SBTi Net-Zero"],
    keyProducts: ["EN-252/14+ MW offshore", "EN-182/6.X onshore", "EnOS AIoT platform", "Envision AESC batteries"],
  },
  "iberdrola-renewables-bilbao": {
    description: "Spanish multinational utility and the world's largest wind energy producer by installed capacity. Active in wind, solar, hydro, and storage across 30+ countries.",
    founded: 1992,
    employees: "~42,000",
    website: "https://www.iberdrola.com",
    email: "accionistas@iberdrola.com",
    phone: "+34-944-151-411",
    address: "Plaza Euskadi 5, 48009 Bilbao, Spain",
    ceo: "Ignacio Galán",
    stockTicker: "IBE (BME)",
    certifications: ["ISO 9001/14001/45001", "SA8000", "GRI Standards", "CDP A-list"],
    keyProducts: ["Offshore wind farms (Baltic Eagle, Saint-Brieuc)", "Onshore wind (global)", "ScottishPower Renewables", "Green hydrogen"],
  },
  "nextera-energy-juno": {
    description: "World's largest generator of wind and solar energy. American utility holding company operating NextEra Energy Resources and Florida Power & Light.",
    founded: 1925,
    employees: "~16,000",
    website: "https://www.nexteraenergy.com",
    email: "investor.relations@nexteraenergy.com",
    phone: "+1-561-694-4000",
    address: "700 Universe Blvd, Juno Beach, FL 33408, USA",
    ceo: "John Ketchum",
    stockTicker: "NEE (NYSE)",
    certifications: ["ISO 14001", "NERC compliance", "FERC regulated", "S&P ESG score 90+"],
    keyProducts: ["Wind farms (30+ GW)", "Solar farms (5+ GW)", "Battery storage (BESS)", "FPL SolarTogether"],
  },
  // ─── HYDRO PRODUCERS ───────────────────────────────────────────────────
  "voith-hydro-heidenheim": {
    description: "German industrial conglomerate division specializing in hydropower equipment. World's leading supplier of turbines, generators, and automation for hydro plants.",
    founded: 1867,
    employees: "~4,500 (Hydro division)",
    website: "https://www.voith.com/hydro",
    email: "info.hydro@voith.com",
    phone: "+49-7321-37-0",
    address: "Alexanderstraße 11, 89522 Heidenheim, Germany",
    ceo: "Uwe Wehnhardt (Voith Hydro President)",
    certifications: ["ISO 9001/14001/45001", "IEC 60034", "OHSAS 18001"],
    keyProducts: ["Francis turbines", "Pelton turbines", "Kaplan turbines", "Pump-turbines (pumped storage)", "HyService digital services"],
  },
  "andritz-hydro-graz": {
    description: "Austrian technology company and one of the world's largest suppliers of electromechanical systems for hydropower. Covers entire range from micro to large hydro.",
    founded: 1852,
    employees: "~8,000 (Hydro division)",
    website: "https://www.andritz.com/hydro",
    email: "hydro@andritz.com",
    phone: "+43-316-6902-0",
    address: "Stattegger Straße 18, 8045 Graz, Austria",
    ceo: "Joachim Schönbeck (Andritz Hydro CEO)",
    stockTicker: "ANDR (VIE)",
    certifications: ["ISO 9001/14001/45001", "IEC 60034", "EN ISO 3834"],
    keyProducts: ["Francis turbines (to 800 MW)", "Pelton turbines", "Bulb/Kaplan turbines", "Pumped storage systems", "Compact hydro (Hydromatrix)"],
  },
  "ge-hydro-grenoble": {
    description: "GE Vernova's hydro division, formerly Alstom Hydro. Installed base of 25%+ of global hydropower capacity. World leader in large Francis turbines.",
    founded: 1917,
    employees: "~3,800",
    website: "https://www.gevernova.com/hydro",
    email: "hydro.info@ge.com",
    phone: "+33-4-7639-2000",
    address: "82 Avenue Léon Blum, 38041 Grenoble Cedex 9, France",
    ceo: "Pascal Radue (GE Hydro VP)",
    stockTicker: "GEV (NYSE)",
    certifications: ["ISO 9001/14001", "IEC 60034", "ASME", "EN 1090"],
    keyProducts: ["Francis turbines (to 1000 MW)", "Pelton turbines", "Kaplan/Bulb turbines", "Variable-speed pump storage", "HydroAMP digital solution"],
  },
  "statkraft-oslo": {
    description: "Europe's largest generator of renewable energy. Norwegian state-owned company operating hydropower, wind, solar, and gas across 20 countries.",
    founded: 1895,
    employees: "~5,500",
    website: "https://www.statkraft.com",
    email: "info@statkraft.com",
    phone: "+47-24-06-70-00",
    address: "Lilleakerveien 6, 0216 Oslo, Norway",
    ceo: "Christian Rynning-Tønnesen",
    certifications: ["ISO 9001/14001/45001", "BREEAM Excellent", "SBTi Net-Zero", "CDP A-list"],
    keyProducts: ["Hydropower (340+ plants)", "Onshore wind", "Solar PV", "Green hydrogen", "Power trading"],
  },
  "norsk-hydro-bergen": {
    description: "Originally a hydropower and fertilizer company, now focused on aluminum and renewables. Retains significant hydro generation capacity in Norway.",
    founded: 1905,
    employees: "~33,000",
    website: "https://www.hydro.com",
    email: "contact@hydro.com",
    phone: "+47-22-53-81-00",
    address: "Drammensveien 264, 0283 Oslo, Norway",
    ceo: "Hilde Merete Aasheim",
    stockTicker: "NHY (OSE)",
    certifications: ["ISO 9001/14001/45001", "ASI (Aluminium Stewardship)", "SBTi"],
    keyProducts: ["Hydro Rein (renewables)", "Hydropower plants", "Low-carbon aluminum", "Hydro CIRCAL recycled aluminum"],
  },
  "itaipu-foz-do-iguacu": {
    description: "World's largest hydropower plant by annual generation (~76 TWh/yr). Binational entity shared between Brazil and Paraguay on the Paraná River.",
    founded: 1984,
    employees: "~3,200",
    website: "https://www.itaipu.gov.br",
    email: "faleconosco@itaipu.gov.br",
    phone: "+55-45-3520-5252",
    address: "Av. Tancredo Neves, 6731, Foz do Iguaçu, PR 85866-900, Brazil",
    ceo: "Enio Verri (Director General)",
    certifications: ["ISO 9001/14001", "SA8000", "GRI Standards"],
    keyProducts: ["14 GW installed capacity", "20 Francis turbines (700 MW each)", "Cross-border energy supply", "Environmental conservation"],
  },
  "three-gorges-yichang": {
    description: "Operates the Three Gorges Dam (22.5 GW) and is the world's largest hydropower operator. Also expanding into offshore wind and international renewable projects.",
    founded: 1993,
    employees: "~25,000",
    website: "https://www.ctg.com.cn",
    email: "ir@ctg.com.cn",
    phone: "+86-717-672-4330",
    address: "1 Jianshe Road, Yichang, Hubei 443002, China",
    ceo: "Lei Mingshan",
    stockTicker: "600900 (SSE)",
    certifications: ["ISO 9001/14001/45001", "GRI Standards", "CDP"],
    keyProducts: ["Three Gorges Dam (22.5 GW)", "Baihetan Dam (16 GW)", "Xiluodu Dam (13.9 GW)", "Offshore wind farms", "International hydro projects"],
  },
  "hydro-quebec-montreal": {
    description: "Provincial crown corporation and one of the largest hydropower producers in the world. Almost all of Québec's electricity (>99%) comes from hydro.",
    founded: 1944,
    employees: "~22,000",
    website: "https://www.hydroquebec.com",
    email: "info@hydroquebec.com",
    phone: "+1-514-289-2211",
    address: "75 Boul. René-Lévesque Ouest, Montréal, QC H2Z 1A4, Canada",
    ceo: "Michael Sabia",
    certifications: ["ISO 14001", "BOMA BEST", "GRI Standards", "CDP A-list"],
    keyProducts: ["37.3 GW hydro capacity", "La Grande complex", "Manic-Outardes complex", "Churchill Falls", "Cross-border exports to US"],
  },
  "vattenfall-stockholm": {
    description: "Swedish state-owned energy company, one of Europe's largest producers. Strong in hydro (Sweden), wind (North Sea), and nuclear. Expanding solar.",
    founded: 1909,
    employees: "~20,000",
    website: "https://www.vattenfall.com",
    email: "info@vattenfall.com",
    phone: "+46-8-739-50-00",
    address: "Evenemangsgatan 13, 169 92 Solna, Sweden",
    ceo: "Anna Borg",
    certifications: ["ISO 9001/14001/45001", "EMAS", "SBTi", "CDP A-list"],
    keyProducts: ["Hydropower (Sweden, 12 GW)", "Offshore wind (Hollandse Kust, Horns Rev)", "Onshore wind", "District heating"],
  },
  "toshiba-hydro-tokyo": {
    description: "Toshiba Energy Systems' hydro division manufactures turbines and generators for large-scale hydro plants. Historical installations include Hoover Dam equipment.",
    founded: 1875,
    employees: "~3,000 (energy systems)",
    website: "https://www.global.toshiba/ww/products-solutions/renewable-energy/products/hydro.html",
    email: "hydro-info@toshiba.co.jp",
    phone: "+81-44-331-0625",
    address: "1-1 Shibaura, Minato-ku, Tokyo 105-8001, Japan",
    ceo: "Taro Shimada (Toshiba CEO)",
    certifications: ["ISO 9001/14001", "IEC 60034", "JIS standards", "ASME"],
    keyProducts: ["Francis turbines", "Pelton turbines", "Kaplan turbines", "Pump-turbines", "Hydro generators (to 700 MW)"],
  },
  // ─── BIOMASS/BIOGAS PRODUCERS ──────────────────────────────────────────
  "envitec-biogas-lohne": {
    description: "World's leading biogas plant manufacturer and operator. German company offering turn-key plants from planning through operation, plus biogas upgrading to biomethane.",
    founded: 2002,
    employees: "~500",
    website: "https://www.envitec-biogas.com",
    email: "info@envitec-biogas.de",
    phone: "+49-4442-8016-8100",
    address: "Industriering 10a, 49393 Lohne, Germany",
    ceo: "Olaf von Lehmden",
    stockTicker: "ETG (XETRA)",
    certifications: ["ISO 9001/14001", "EEG certified", "GasNZV compliant"],
    keyProducts: ["Turn-key biogas plants", "Biogas upgrading (biomethane)", "EnviTec substrate feedstock", "Plant operation services"],
  },
  "weltec-biopower-vechta": {
    description: "German manufacturer of stainless-steel biogas and biomethane plants. Known for modular, relocatable plant designs and waste-to-energy solutions.",
    founded: 2001,
    employees: "~100",
    website: "https://www.weltec-biopower.com",
    email: "info@weltec-biopower.de",
    phone: "+49-4441-9995-0",
    address: "Zum Langenberg 2, 49377 Vechta, Germany",
    ceo: "Jens Albartus",
    certifications: ["ISO 9001", "DIN EN 1090", "AD 2000 pressure vessels"],
    keyProducts: ["Stainless-steel digesters", "MULTIMix feeding system", "Biomethane upgrading units", "Modular containerized plants"],
  },
  "biogest-vienna": {
    description: "Austrian biogas technology company specializing in anaerobic digestion for agricultural and municipal organic waste. Focus on circular economy solutions.",
    founded: 2005,
    employees: "~80",
    website: "https://www.biogest.at",
    email: "office@biogest.at",
    phone: "+43-1-522-4200",
    address: "Weyrgasse 8, 1030 Wien, Austria",
    ceo: "Thomas Wels",
    certifications: ["ISO 9001", "EMAS", "Austrian Eco-label"],
    keyProducts: ["PowerRing continuous stirred reactor", "FlexBio compact biogas", "BioFermenter dry digestion", "Gas upgrading to biomethane"],
  },
  "nature-energy-odense": {
    description: "Denmark's largest producer of green biogas (biomethane). Converts agricultural residues and organic waste into pipeline-grade renewable gas.",
    founded: 1979,
    employees: "~400",
    website: "https://www.nature-energy.com",
    email: "info@nature-energy.com",
    phone: "+45-7614-7400",
    address: "Ørbækvej 260, 5220 Odense SØ, Denmark",
    ceo: "Ole Hvelplund",
    certifications: ["ISO 14001", "RSB certified", "ISCC EU certified"],
    keyProducts: ["Large-scale biogas plants (40+ MNm³/yr)", "Biomethane grid injection", "Bio-CO₂ capture", "Digestate biofertilizer"],
  },
  "verbio-leipzig": {
    description: "German bioenergy company producing biomethane, bioethanol, and biodiesel. One of Europe's largest independent biofuel producers with own filling stations.",
    founded: 2006,
    employees: "~1,200",
    website: "https://www.verbio.de",
    email: "info@verbio.de",
    phone: "+49-341-308-530-0",
    address: "Augustusplatz 9, 04109 Leipzig, Germany",
    ceo: "Claus Sauter",
    stockTicker: "VBK (XETRA)",
    certifications: ["ISCC EU", "REDcert", "ISO 14001", "EEG certified"],
    keyProducts: ["Biomethane (verbiogas)", "Bioethanol", "Biodiesel (RME)", "Straw-to-biomethane technology"],
  },
  "scandinavian-biogas-stockholm": {
    description: "Nordic leader in large-scale biogas production from food waste, sewage sludge, and industrial organic residues. Supplies vehicle fuel and grid-injected biomethane.",
    founded: 2005,
    employees: "~200",
    website: "https://www.scandinavianbiogas.com",
    email: "info@scandinavianbiogas.com",
    phone: "+46-8-5517-6550",
    address: "Holländargatan 21A, 111 60 Stockholm, Sweden",
    ceo: "Matti Vikkula",
    stockTicker: "BIOGAS (First North)",
    certifications: ["ISO 14001", "RSB certified", "ISCC Plus"],
    keyProducts: ["Biogas upgrading plants", "Vehicle-grade CBG", "Grid biomethane injection", "Industrial waste-to-gas"],
  },
  "drax-group-selby": {
    description: "UK's largest renewable electricity generator, converted from coal to biomass. Burns compressed wood pellets with BECCS (bioenergy with carbon capture) pilot.",
    founded: 1974,
    employees: "~3,800",
    website: "https://www.drax.com",
    email: "info@drax.com",
    phone: "+44-1757-618-381",
    address: "Drax Power Station, Selby, North Yorkshire YO8 8PH, UK",
    ceo: "Will Gardiner",
    stockTicker: "DRX (LSE)",
    certifications: ["ISO 14001/45001", "SBP certified biomass", "OFGEM ROCs", "EU ETS compliant"],
    keyProducts: ["Biomass power (2.6 GW)", "BECCS carbon capture pilot", "Compressed wood pellets", "Pumped storage hydro (Cruachan)"],
  },
  "epe-renewables-osaka": {
    description: "Japanese bio-energy developer converting food waste, agricultural residues, and sewage to electricity and heat via anaerobic digestion and gasification.",
    founded: 2012,
    employees: "~150",
    website: "https://www.jbioenergy.co.jp",
    email: "info@jbioenergy.co.jp",
    phone: "+81-6-6445-0120",
    address: "2-3-4 Nakanoshima, Kita-ku, Osaka 530-0005, Japan",
    ceo: "Takeshi Morimoto",
    certifications: ["ISO 14001", "J-Credit certified", "FIT approved"],
    keyProducts: ["Food waste digestion plants", "Woody biomass gasification", "Biogas CHP systems", "Digestate fertilizer"],
  },
  // ─── GEOTHERMAL PRODUCERS ──────────────────────────────────────────────
  "ormat-technologies-reno": {
    description: "Global leader in geothermal energy with proprietary ORC (Organic Rankine Cycle) technology. Designs, builds, and operates geothermal plants worldwide.",
    founded: 1965,
    employees: "~1,700",
    website: "https://www.ormat.com",
    email: "info@ormat.com",
    phone: "+1-775-356-9029",
    address: "6140 Plumas Street, Reno, NV 89519, USA",
    ceo: "Doron Blachar",
    stockTicker: "ORA (NYSE)",
    certifications: ["ISO 9001/14001/45001", "CARB compliant", "RPS eligible"],
    keyProducts: ["ORC geothermal power plants", "Recovered Energy Generation (REG)", "Energy storage", "Puna & Olkaria operations"],
  },
  "enel-geothermal-pisa": {
    description: "Enel's geothermal operations in Tuscany, Italy — birthplace of commercial geothermal energy (Larderello, 1911). World's oldest geothermal field still in operation.",
    founded: 1904,
    employees: "~800",
    website: "https://www.enelgreenpower.com/geothermal",
    email: "geothermal@enel.com",
    phone: "+39-050-616-1",
    address: "Via Andrea Pisano 120, 56122 Pisa, Italy",
    ceo: "Part of Enel Green Power",
    stockTicker: "ENEL.MI (parent)",
    certifications: ["ISO 9001/14001/45001", "EMAS"],
    keyProducts: ["Larderello geothermal complex", "Monte Amiata plants", "Flash steam technology", "Binary cycle units", "Geothermal heat for greenhouses"],
  },
  "on-power-reykjavik": {
    description: "Icelandic geothermal utility providing electricity and hot water to Reykjavik. Operates Hellisheiði (303 MW), one of the world's largest geothermal plants.",
    founded: 2014,
    employees: "~400",
    website: "https://www.on.is",
    email: "on@on.is",
    phone: "+354-516-6000",
    address: "Bæjarhálsi 1, 110 Reykjavik, Iceland",
    ceo: "Bjarni Bjarnason",
    certifications: ["ISO 14001/50001", "Equator Principles"],
    keyProducts: ["Hellisheiði plant (303 MW + 133 MW thermal)", "Nesjavellir plant", "CarbFix CO₂ mineralization", "District heating (hot water)"],
  },
  "pertamina-geo-jakarta": {
    description: "Indonesia's state-owned geothermal company — world's second-largest geothermal country by installed capacity (2.4 GW). Operates along the Pacific Ring of Fire.",
    founded: 2006,
    employees: "~1,500",
    website: "https://www.pertaminageothermal.com",
    email: "info@pertaminageothermal.com",
    phone: "+62-21-2950-1700",
    address: "Menara Cakrawala, Jl. MH Thamrin 9, Jakarta 10340, Indonesia",
    ceo: "Ahmad Fauzi",
    stockTicker: "PGEO (IDX)",
    certifications: ["ISO 9001/14001/45001", "PROPER Green rating", "IDX ESG certified"],
    keyProducts: ["Kamojang geothermal field", "Lahendong field", "Ulubelu field", "Karaha Bodas field"],
  },
  "contact-energy-taupo": {
    description: "New Zealand's largest geothermal generator, operating in the Taupō Volcanic Zone. Over 60% of generation from geothermal, with balance from hydro and gas.",
    founded: 1996,
    employees: "~1,100",
    website: "https://www.contactenergy.co.nz",
    email: "investor@contactenergy.co.nz",
    phone: "+64-4-499-4001",
    address: "Harbour City Tower, 29 Brandon Street, Wellington 6011, New Zealand",
    ceo: "Mike Fuge",
    stockTicker: "CEN (NZX)",
    certifications: ["ISO 14001", "Toitū carbon neutral", "NZGBC Green Star"],
    keyProducts: ["Wairakei geothermal complex", "Te Mihi power station", "Tauhara (under construction)", "Clyde Dam hydro"],
  },
  "kengen-naivasha": {
    description: "Kenya's largest power producer, generating over 80% of national electricity. Major geothermal operations in the Great Rift Valley (Olkaria complex).",
    founded: 1954,
    employees: "~2,500",
    website: "https://www.kengen.co.ke",
    email: "info@kengen.co.ke",
    phone: "+254-20-3666-000",
    address: "KenGen, Stima Plaza, Kolobot Road, Nairobi, Kenya",
    ceo: "Peter Njenga",
    stockTicker: "KEGN (NSE Kenya)",
    certifications: ["ISO 9001/14001/45001", "UN CDM certified"],
    keyProducts: ["Olkaria geothermal complex (860 MW)", "Hydro dams (Tana River)", "Wind (Lake Turkana contribution)", "Geothermal direct use"],
  },
  "star-energy-bandung": {
    description: "Indonesia-based geothermal developer operating the Wayang Windu and Salak fields. Uses flash and binary cycle technology for efficient extraction.",
    founded: 2010,
    employees: "~800",
    website: "https://www.starenergy.co.id",
    email: "info@starenergy.co.id",
    phone: "+62-22-7800-200",
    address: "Jl. Cihampelas Walk, Bandung 40131, West Java, Indonesia",
    ceo: "Hendra Tan",
    certifications: ["ISO 9001/14001/45001", "PROPER Blue-Green", "CDM registered"],
    keyProducts: ["Wayang Windu geothermal (227 MW)", "Salak geothermal (377 MW)", "Binary cycle units", "Condensate recovery systems"],
  },
  // ─── HYBRID / STORAGE PRODUCERS ────────────────────────────────────────
  "tesla-energy-austin": {
    description: "Tesla's energy division producing Megapack utility storage, Powerwall home batteries, and Solar Roof. One of the largest BESS deployers globally.",
    founded: 2015,
    employees: "Part of Tesla (~140,000 total)",
    website: "https://www.tesla.com/energy",
    email: "energysupport@tesla.com",
    phone: "+1-888-518-3752",
    address: "Giga Texas, 13101 Harold Green Road, Austin, TX 78725, USA",
    ceo: "Elon Musk (Tesla CEO)",
    stockTicker: "TSLA (NASDAQ)",
    certifications: ["UL 9540", "IEC 62619", "UL 1741 SA", "IEEE 1547"],
    keyProducts: ["Megapack 2 XL (3.9 MWh)", "Powerwall 3 (13.5 kWh)", "Solar Roof (Gen 3)", "Tesla Solar Inverter", "Autobidder AI platform"],
  },
  "byd-energy-shenzhen": {
    description: "Chinese tech conglomerate — world's largest EV maker and major battery manufacturer. BYD Energy offers utility-scale BESS, solar panels, and microgrids.",
    founded: 1995,
    employees: "~700,000",
    website: "https://www.byd.com/en/energy",
    email: "energy@byd.com",
    phone: "+86-755-8988-8888",
    address: "BYD Industrial Park, Pingshan, Shenzhen 518118, China",
    ceo: "Wang Chuanfu",
    stockTicker: "1211.HK / 002594 (SZSE)",
    certifications: ["IEC 62619", "UL 9540", "ISO 9001/14001", "UN38.3"],
    keyProducts: ["BatteryBox residential storage", "MC Cube containerized BESS", "Blade Battery LFP cells", "Solar panels", "SkyRail & SkyShuttle"],
  },
  "sonnen-wildpoldsried": {
    description: "German pioneer in residential batteries and virtual power plant (VPP) communities. Part of Shell since 2019. Famous for making Wildpoldsried energy-independent.",
    founded: 2010,
    employees: "~800",
    website: "https://www.sonnen.de",
    email: "info@sonnen.de",
    phone: "+49-8379-6654-0",
    address: "Am Riedbach 1, 87499 Wildpoldsried, Germany",
    ceo: "Oliver Koch",
    certifications: ["IEC 62619", "TÜV Rheinland", "ISO 9001", "VDE certified"],
    keyProducts: ["sonnenBatterie 10", "sonnenBatterie eco 8", "sonnenFlat community tariff", "sonnenVPP virtual power plant", "sonnenProtect backup"],
  },
  "fluence-energy-arlington": {
    description: "Joint venture of Siemens and AES — one of the world's largest pure-play energy storage companies. Provides utility-scale BESS, software, and services.",
    founded: 2018,
    employees: "~1,500",
    website: "https://www.fluenceenergy.com",
    email: "info@fluenceenergy.com",
    phone: "+1-833-358-3623",
    address: "4601 Fairfax Drive, Suite 600, Arlington, VA 22203, USA",
    ceo: "Julian Nebreda",
    stockTicker: "FLNC (NASDAQ)",
    certifications: ["UL 9540", "IEC 62619", "NFPA 855", "ISO 9001"],
    keyProducts: ["Gridstack utility BESS", "Edgestack C&I BESS", "Mosaic AI bidding platform", "Nispera asset management"],
  },
  "sungrow-hefei": {
    description: "World's largest inverter manufacturer by shipments, now also a major player in energy storage. Chinese company with products in 170+ countries.",
    founded: 1997,
    employees: "~12,000",
    website: "https://www.sungrowpower.com",
    email: "info@sungrow.cn",
    phone: "+86-551-6532-7808",
    address: "No. 1699 Xiyou Road, Hefei 230088, Anhui, China",
    ceo: "Cao Renxian",
    stockTicker: "300274 (SZSE ChiNext)",
    certifications: ["IEC 62109", "IEC 62619", "UL 1741/9540", "ISO 9001/14001"],
    keyProducts: ["SG250/350HX-US string inverters", "SG3150/4400U central inverters", "PowerTitan 2.0 liquid-cooled BESS", "FPV floating solar solutions"],
  },
  "iberdrola-hybrid-madrid": {
    description: "Iberdrola's integrated renewables operation from Madrid, managing hybrid wind-solar-storage projects across Spain, UK, US, and Latin America.",
    founded: 1992,
    employees: "Part of Iberdrola (~42,000)",
    website: "https://www.iberdrola.com/sustainability/renewable-energy",
    email: "accionistas@iberdrola.com",
    phone: "+34-91-784-4400",
    address: "Calle Tomás Redondo 1, 28033 Madrid, Spain",
    ceo: "Ignacio Galán",
    stockTicker: "IBE (BME)",
    certifications: ["ISO 9001/14001/45001", "GRI Standards", "CDP A-list", "SBTi"],
    keyProducts: ["Hybrid wind+solar parks", "Battery storage (200 MW+ UK)", "Green hydrogen (Puertollano)", "Smart Solar communities"],
  },
  "totalenergies-paris": {
    description: "French energy major transformed into multi-energy company. Target: 100 GW renewables by 2030. Active in solar, wind, and battery storage globally.",
    founded: 1924,
    employees: "~100,000",
    website: "https://www.totalenergies.com",
    email: "renewable.energies@totalenergies.com",
    phone: "+33-1-4744-4546",
    address: "2 Place Jean Millier, 92078 Paris La Défense, France",
    ceo: "Patrick Pouyanné",
    stockTicker: "TTE (Euronext / NYSE)",
    certifications: ["ISO 9001/14001/45001", "GRI Standards", "SBTi", "CDP A"],
    keyProducts: ["Utility solar farms (40+ GW pipeline)", "Offshore wind", "BESS storage", "SunPower residential (US)", "Green hydrogen"],
  },
  "acciona-energia-madrid": {
    description: "Spanish renewable energy developer and producer — exclusively renewable, no fossil assets. Pioneer since 1989 with presence in 20+ countries.",
    founded: 1989,
    employees: "~3,200",
    website: "https://www.acciona-energia.com",
    email: "info.energia@acciona.com",
    phone: "+34-91-663-2850",
    address: "Avenida de Europa 18, Parque Empresarial La Moraleja, 28108 Madrid, Spain",
    ceo: "Rafael Mateo Alcalá",
    stockTicker: "ANE (BME)",
    certifications: ["ISO 9001/14001/45001", "AENOR certified", "GRI Standards", "SBTi"],
    keyProducts: ["Wind farms (onshore, 9+ GW)", "Solar PV (utility-scale)", "Hybrid wind-solar-storage", "Green hydrogen"],
  },
  // ─── EQUIPMENT MANUFACTURERS ───────────────────────────────────────────
  "sma-solar-niestetal": {
    description: "World's leading specialist in photovoltaic inverter technology with 120+ GW installed. German company offering residential, commercial, and utility-scale solutions.",
    founded: 1981,
    employees: "~4,200",
    website: "https://www.sma.de",
    email: "info@sma.de",
    phone: "+49-561-9522-0",
    address: "Sonnenallee 1, 34266 Niestetal, Germany",
    ceo: "Jürgen Reinert",
    stockTicker: "S92 (XETRA)",
    certifications: ["IEC 62109", "UL 1741 SA", "VDE-AR-N 4105", "ISO 9001/14001"],
    keyProducts: ["Sunny Boy residential inverters", "Sunny Tripower commercial", "Sunny Central utility (up to 6.6 MW)", "Sunny Portal monitoring"],
  },
  "fronius-pettenbach": {
    description: "Austrian family-owned company, global leader in hybrid inverters combining solar, battery, and grid. Also known for welding technology and battery charging.",
    founded: 1945,
    employees: "~6,300",
    website: "https://www.fronius.com",
    email: "solar.sales@fronius.com",
    phone: "+43-7242-241-0",
    address: "Froniusstraße 1, 4643 Pettenbach, Austria",
    ceo: "Elisabeth Engelbrechtsmüller-Strauß",
    certifications: ["IEC 62109", "VDE-AR-N 4105", "AS4777", "ISO 9001/14001"],
    keyProducts: ["GEN24 Plus hybrid inverters", "Tauro commercial inverters", "Symo Advanced string", "Wattpilot EV charger", "Solar.web monitoring"],
  },
  "huawei-fusionsolar-shenzhen": {
    description: "Huawei's smart PV division — world's #1 inverter shipper by volume. Combines AI, power electronics, and cloud for solar+storage solutions.",
    founded: 2013,
    employees: "Part of Huawei (~207,000 total)",
    website: "https://solar.huawei.com",
    email: "fusionsolar@huawei.com",
    phone: "+86-755-2878-0808",
    address: "Huawei Base, Bantian, Longgang, Shenzhen 518129, China",
    ceo: "Part of Huawei (Ren Zhengfei, founder)",
    certifications: ["IEC 62109", "IEC 62619", "UL 1741 SA", "TÜV Rheinland"],
    keyProducts: ["SUN2000 residential inverters", "SUN2000 utility (215 kW+)", "LUNA2000 home battery", "SmartLogger 3000A", "FusionSolar app"],
  },
  "goodwe-suzhou": {
    description: "Chinese inverter specialist and one of the world's top 5 PV inverter brands. Strong in residential hybrid systems combining solar, battery, and EV charging.",
    founded: 2010,
    employees: "~4,000",
    website: "https://www.goodwe.com",
    email: "sales@goodwe.com",
    phone: "+86-512-6269-0600",
    address: "No. 90 Zijin Road, Suzhou 215011, Jiangsu, China",
    ceo: "Huang Min",
    stockTicker: "688390 (SSE STAR)",
    certifications: ["IEC 62109", "VDE-AR-N 4105", "UL 1741", "ISO 9001/14001"],
    keyProducts: ["ET Plus+ hybrid inverters", "SDT G2 string inverters", "HT commercial inverters", "Lynx Home battery", "SEMS monitoring"],
  },
  "growatt-shenzhen": {
    description: "One of the world's top 10 inverter manufacturers. Chinese company strong in residential and C&I segments, with growing energy storage portfolio.",
    founded: 2010,
    employees: "~5,000",
    website: "https://www.growatt.com",
    email: "info@growatt.com",
    phone: "+86-755-2747-1942",
    address: "Building A, Jiayu Industrial Park, Shenzhen 518116, China",
    ceo: "David Ding",
    certifications: ["IEC 62109", "UL 1741", "VDE", "ISO 9001/14001"],
    keyProducts: ["MIN series residential inverters", "MOD XH hybrid inverters", "MID 33-50kTL commercial", "ARK battery system", "ShinePhone app"],
  },
  "catl-ningde": {
    description: "World's largest EV and energy storage battery manufacturer by capacity. Chinese company supplying Tesla, BMW, VW, and major utility BESS projects globally.",
    founded: 2011,
    employees: "~130,000",
    website: "https://www.catl.com",
    email: "ir@catl.com",
    phone: "+86-593-898-9999",
    address: "No. 2 Xingang Road, Ningde, Fujian 352100, China",
    ceo: "Robin Zeng (Zeng Yuqun)",
    stockTicker: "300750 (SZSE ChiNext)",
    certifications: ["ISO 9001/14001/45001", "IATF 16949", "IEC 62619", "UL 9540"],
    keyProducts: ["EnerOne outdoor BESS cabinet", "EnerC containerized BESS", "Qilin CTP 3.0 cells", "Sodium-ion batteries", "Shenxing fast-charge LFP"],
  },
  "lg-energy-solution-seoul": {
    description: "World's second-largest EV battery maker, spun off from LG Chem. Major supplier to GM, Hyundai, Tesla. Growing residential and utility ESS business.",
    founded: 2020,
    employees: "~30,000",
    website: "https://www.lgensol.com",
    email: "contact@lgensol.com",
    phone: "+82-2-3773-1114",
    address: "LG Science Park, 30 Magok-jungang 10-ro, Gangseo-gu, Seoul, Korea",
    ceo: "Kwon Young-soo",
    stockTicker: "373220 (KRX)",
    certifications: ["ISO 9001/14001/45001", "IATF 16949", "IEC 62619", "UL 9540"],
    keyProducts: ["RESU residential battery (10/16 kWh)", "RESU Prime series", "Enblock containerized ESS", "NMC pouch cells", "LFP prismatic cells"],
  },
  "victron-energy-almere": {
    description: "Dutch manufacturer of off-grid and marine power systems. Known for robust, modular inverter/chargers and comprehensive monitoring. Strong in boats, RVs, and telecom.",
    founded: 1975,
    employees: "~800",
    website: "https://www.victronenergy.com",
    email: "sales@victronenergy.com",
    phone: "+31-36-535-9700",
    address: "De Paal 35, 1351 JG Almere, Netherlands",
    ceo: "Matthijs Vader",
    certifications: ["IEC 62109", "EN 50549", "AS4777", "DNV Maritime"],
    keyProducts: ["MultiPlus-II inverter/charger", "SmartSolar MPPT controllers", "Cerbo GX monitoring", "Lynx Smart BMS", "Blue Smart IP65 chargers"],
  },
  "nextracker-fremont": {
    description: "World's #1 solar tracker company (spin-off from Flex). Single-axis trackers that tilt panels to follow the sun, increasing energy yield by 20-25%.",
    founded: 2013,
    employees: "~2,500",
    website: "https://www.nextracker.com",
    email: "sales@nextracker.com",
    phone: "+1-510-270-2500",
    address: "6200 Paseo Padre Pkwy, Fremont, CA 94555, USA",
    ceo: "Dan Shugar",
    stockTicker: "NXT (NASDAQ)",
    certifications: ["UL 3703", "IEC 62817", "ISO 9001", "AS/NZS 1170"],
    keyProducts: ["NX Horizon single-axis tracker", "NX Gemini split-architecture", "TrueCapture software", "NX Hail Pro protection", "NX Flow wind load reduction"],
  },
  "hitachi-energy-zurich": {
    description: "Global leader in power grids, transformers, and HVDC technology. Created from ABB's Power Grids division acquired by Hitachi. Enables renewable grid integration.",
    founded: 2020,
    employees: "~42,000",
    website: "https://www.hitachienergy.com",
    email: "contact-us@hitachienergy.com",
    phone: "+41-58-585-5100",
    address: "Bruggerstrasse 72, 5400 Baden, Switzerland",
    ceo: "Andreas Schierenbeck",
    certifications: ["ISO 9001/14001/45001", "IEC 61850", "IEC 61968", "SBTi"],
    keyProducts: ["HVDC Light converter stations", "Power transformers (to 1200 MVA)", "e-mesh BESS integration", "Grid-eConomy digital substations", "EconiQ eco-switchgear"],
  },
  "schneider-electric-paris": {
    description: "French multinational — world leader in energy management and industrial automation. Strong in microgrids, building energy, and medium-voltage grid equipment.",
    founded: 1836,
    employees: "~150,000",
    website: "https://www.se.com",
    email: "contact@se.com",
    phone: "+33-1-4129-7000",
    address: "35 rue Joseph Monier, 92500 Rueil-Malmaison, France",
    ceo: "Peter Herweck",
    stockTicker: "SU (Euronext Paris)",
    certifications: ["ISO 9001/14001/45001/50001", "IEC 61850", "GRI Standards", "CDP A-list"],
    keyProducts: ["Conext utility inverters", "Premset MV switchgear", "EcoStruxure Microgrid", "PowerLogic metering", "Galaxy UPS"],
  },
  "staubli-pfaffikon": {
    description: "Swiss industrial connector company — inventor and sole original manufacturer of the MC4 connector, the global standard for solar panel interconnection.",
    founded: 1892,
    employees: "~6,000",
    website: "https://www.staubli.com/solar",
    email: "ec.sales@staubli.com",
    phone: "+41-44-928-5151",
    address: "Seestrasse 280, 8810 Horgen, Switzerland",
    ceo: "Rolf Strebel",
    certifications: ["TÜV certified", "UL 6703", "IEC 62852", "ISO 9001"],
    keyProducts: ["MC4 original solar connectors", "MC4-Evo 2 next-gen", "MC-PV branch & Y-connectors", "CombiTac modular", "Quick-lock coupling systems"],
  },
  "prysmian-milan": {
    description: "World's largest cable manufacturer. Produces submarine HVDC cables for offshore wind farms, solar DC cables, and grid interconnectors enabling renewables.",
    founded: 1879,
    employees: "~30,000",
    website: "https://www.prysmiangroup.com",
    email: "info@prysmiangroup.com",
    phone: "+39-02-6449-1",
    address: "Via Chiese 6, 20126 Milan, Italy",
    ceo: "Massimo Battaini",
    stockTicker: "PRY (BIT)",
    certifications: ["ISO 9001/14001/45001", "IEC 60502", "DNV Maritime", "CIGRE"],
    keyProducts: ["P-Sun solar string cables", "Submarine HVDC cables (525 kV)", "Offshore wind array cables", "MV distribution cables", "Fiber optic monitoring"],
  },
};
